/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as TyreGuideRouteImport } from './routes/tyre-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LubricantsRouteImport } from './routes/lubricants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTestingLabRouteImport } from './routes/admin.testing-lab'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTyresRouteImport } from './routes/_authenticated/admin.tyres'
import { Route as AuthenticatedAdminChangePasswordRouteImport } from './routes/_authenticated/admin.change-password'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminTyresIndexRouteImport } from './routes/_authenticated/admin.tyres.index'
import { Route as AuthenticatedAdminBrandsIndexRouteImport } from './routes/_authenticated/admin.brands.index'
import { Route as AuthenticatedAdminTyresNewRouteImport } from './routes/_authenticated/admin.tyres.new'
import { Route as AuthenticatedAdminTyresIdRouteImport } from './routes/_authenticated/admin.tyres.$id'
import { Route as AuthenticatedAdminBrandsNewRouteImport } from './routes/_authenticated/admin.brands.new'
import { Route as AuthenticatedAdminBrandsIdRouteImport } from './routes/_authenticated/admin.brands.$id'

const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const TyreGuideRoute = TyreGuideRouteImport.update({
  id: '/tyre-guide',
  path: '/tyre-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LubricantsRoute = LubricantsRouteImport.update({
  id: '/lubricants',
  path: '/lubricants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestingLabRoute = AdminTestingLabRouteImport.update({
  id: '/admin/testing-lab',
  path: '/admin/testing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTyresRoute = AuthenticatedAdminTyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminChangePasswordRoute =
  AuthenticatedAdminChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTyresIndexRoute =
  AuthenticatedAdminTyresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminBrandsIndexRoute =
  AuthenticatedAdminBrandsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)
const AuthenticatedAdminTyresNewRoute =
  AuthenticatedAdminTyresNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminTyresIdRoute =
  AuthenticatedAdminTyresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminBrandsNewRoute =
  AuthenticatedAdminBrandsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)
const AuthenticatedAdminBrandsIdRoute =
  AuthenticatedAdminBrandsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRouteWithChildren
  '/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/admin/tyres': typeof AuthenticatedAdminTyresRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRoute
  '/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/admin/brands/': typeof AuthenticatedAdminBrandsIndexRoute
  '/admin/tyres/': typeof AuthenticatedAdminTyresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRoute
  '/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsIndexRoute
  '/admin/tyres': typeof AuthenticatedAdminTyresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRouteWithChildren
  '/_authenticated/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/_authenticated/admin/tyres': typeof AuthenticatedAdminTyresRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/_authenticated/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/_authenticated/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRoute
  '/_authenticated/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/_authenticated/admin/brands/': typeof AuthenticatedAdminBrandsIndexRoute
  '/_authenticated/admin/tyres/': typeof AuthenticatedAdminTyresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/lubricants'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin'
    | '/admin/testing-lab'
    | '/admin/brands'
    | '/admin/change-password'
    | '/admin/tyres'
    | '/admin/'
    | '/admin/brands/$id'
    | '/admin/brands/new'
    | '/admin/tyres/$id'
    | '/admin/tyres/new'
    | '/admin/brands/'
    | '/admin/tyres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/lubricants'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin/testing-lab'
    | '/admin/change-password'
    | '/admin'
    | '/admin/brands/$id'
    | '/admin/brands/new'
    | '/admin/tyres/$id'
    | '/admin/tyres/new'
    | '/admin/brands'
    | '/admin/tyres'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/lubricants'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/_authenticated/admin'
    | '/admin/testing-lab'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/change-password'
    | '/_authenticated/admin/tyres'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/brands/$id'
    | '/_authenticated/admin/brands/new'
    | '/_authenticated/admin/tyres/$id'
    | '/_authenticated/admin/tyres/new'
    | '/_authenticated/admin/brands/'
    | '/_authenticated/admin/tyres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LubricantsRoute: typeof LubricantsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TyreGuideRoute: typeof TyreGuideRoute
  TyresRoute: typeof TyresRoute
  AdminTestingLabRoute: typeof AdminTestingLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyre-guide': {
      id: '/tyre-guide'
      path: '/tyre-guide'
      fullPath: '/tyre-guide'
      preLoaderRoute: typeof TyreGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lubricants': {
      id: '/lubricants'
      path: '/lubricants'
      fullPath: '/lubricants'
      preLoaderRoute: typeof LubricantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testing-lab': {
      id: '/admin/testing-lab'
      path: '/admin/testing-lab'
      fullPath: '/admin/testing-lab'
      preLoaderRoute: typeof AdminTestingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tyres': {
      id: '/_authenticated/admin/tyres'
      path: '/tyres'
      fullPath: '/admin/tyres'
      preLoaderRoute: typeof AuthenticatedAdminTyresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/change-password': {
      id: '/_authenticated/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AuthenticatedAdminChangePasswordRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tyres/': {
      id: '/_authenticated/admin/tyres/'
      path: '/'
      fullPath: '/admin/tyres/'
      preLoaderRoute: typeof AuthenticatedAdminTyresIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/brands/': {
      id: '/_authenticated/admin/brands/'
      path: '/'
      fullPath: '/admin/brands/'
      preLoaderRoute: typeof AuthenticatedAdminBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
    '/_authenticated/admin/tyres/new': {
      id: '/_authenticated/admin/tyres/new'
      path: '/new'
      fullPath: '/admin/tyres/new'
      preLoaderRoute: typeof AuthenticatedAdminTyresNewRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/tyres/$id': {
      id: '/_authenticated/admin/tyres/$id'
      path: '/$id'
      fullPath: '/admin/tyres/$id'
      preLoaderRoute: typeof AuthenticatedAdminTyresIdRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/brands/new': {
      id: '/_authenticated/admin/brands/new'
      path: '/new'
      fullPath: '/admin/brands/new'
      preLoaderRoute: typeof AuthenticatedAdminBrandsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
    '/_authenticated/admin/brands/$id': {
      id: '/_authenticated/admin/brands/$id'
      path: '/$id'
      fullPath: '/admin/brands/$id'
      preLoaderRoute: typeof AuthenticatedAdminBrandsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
  }
}

interface AuthenticatedAdminBrandsRouteChildren {
  AuthenticatedAdminBrandsIdRoute: typeof AuthenticatedAdminBrandsIdRoute
  AuthenticatedAdminBrandsNewRoute: typeof AuthenticatedAdminBrandsNewRoute
  AuthenticatedAdminBrandsIndexRoute: typeof AuthenticatedAdminBrandsIndexRoute
}

const AuthenticatedAdminBrandsRouteChildren: AuthenticatedAdminBrandsRouteChildren =
  {
    AuthenticatedAdminBrandsIdRoute: AuthenticatedAdminBrandsIdRoute,
    AuthenticatedAdminBrandsNewRoute: AuthenticatedAdminBrandsNewRoute,
    AuthenticatedAdminBrandsIndexRoute: AuthenticatedAdminBrandsIndexRoute,
  }

const AuthenticatedAdminBrandsRouteWithChildren =
  AuthenticatedAdminBrandsRoute._addFileChildren(
    AuthenticatedAdminBrandsRouteChildren,
  )

interface AuthenticatedAdminTyresRouteChildren {
  AuthenticatedAdminTyresIdRoute: typeof AuthenticatedAdminTyresIdRoute
  AuthenticatedAdminTyresNewRoute: typeof AuthenticatedAdminTyresNewRoute
  AuthenticatedAdminTyresIndexRoute: typeof AuthenticatedAdminTyresIndexRoute
}

const AuthenticatedAdminTyresRouteChildren: AuthenticatedAdminTyresRouteChildren =
  {
    AuthenticatedAdminTyresIdRoute: AuthenticatedAdminTyresIdRoute,
    AuthenticatedAdminTyresNewRoute: AuthenticatedAdminTyresNewRoute,
    AuthenticatedAdminTyresIndexRoute: AuthenticatedAdminTyresIndexRoute,
  }

const AuthenticatedAdminTyresRouteWithChildren =
  AuthenticatedAdminTyresRoute._addFileChildren(
    AuthenticatedAdminTyresRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRouteWithChildren
  AuthenticatedAdminChangePasswordRoute: typeof AuthenticatedAdminChangePasswordRoute
  AuthenticatedAdminTyresRoute: typeof AuthenticatedAdminTyresRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRouteWithChildren,
  AuthenticatedAdminChangePasswordRoute: AuthenticatedAdminChangePasswordRoute,
  AuthenticatedAdminTyresRoute: AuthenticatedAdminTyresRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LubricantsRoute: LubricantsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TyreGuideRoute: TyreGuideRoute,
  TyresRoute: TyresRoute,
  AdminTestingLabRoute: AdminTestingLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
