/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as TyreGuideRouteImport } from './routes/tyre-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LubricantsRouteImport } from './routes/lubricants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTestingLabRouteImport } from './routes/admin.testing-lab'

const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const TyreGuideRoute = TyreGuideRouteImport.update({
  id: '/tyre-guide',
  path: '/tyre-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LubricantsRoute = LubricantsRouteImport.update({
  id: '/lubricants',
  path: '/lubricants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestingLabRoute = AdminTestingLabRouteImport.update({
  id: '/admin/testing-lab',
  path: '/admin/testing-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/admin/testing-lab': typeof AdminTestingLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/admin/testing-lab': typeof AdminTestingLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lubricants': typeof LubricantsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRoute
  '/admin/testing-lab': typeof AdminTestingLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/lubricants'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin/testing-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/lubricants'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin/testing-lab'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/lubricants'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin/testing-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LubricantsRoute: typeof LubricantsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TyreGuideRoute: typeof TyreGuideRoute
  TyresRoute: typeof TyresRoute
  AdminTestingLabRoute: typeof AdminTestingLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyre-guide': {
      id: '/tyre-guide'
      path: '/tyre-guide'
      fullPath: '/tyre-guide'
      preLoaderRoute: typeof TyreGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lubricants': {
      id: '/lubricants'
      path: '/lubricants'
      fullPath: '/lubricants'
      preLoaderRoute: typeof LubricantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testing-lab': {
      id: '/admin/testing-lab'
      path: '/admin/testing-lab'
      fullPath: '/admin/testing-lab'
      preLoaderRoute: typeof AdminTestingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LubricantsRoute: LubricantsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TyreGuideRoute: TyreGuideRoute,
  TyresRoute: TyresRoute,
  AdminTestingLabRoute: AdminTestingLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
