/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TyresRouteImport } from './routes/tyres'
import { Route as TyreGuideRouteImport } from './routes/tyre-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MaintenancePartsRouteImport } from './routes/maintenance-parts'
import { Route as LubricantsRouteImport } from './routes/lubricants'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarCareRouteImport } from './routes/car-care'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdditivesRouteImport } from './routes/additives'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TyresSlugRouteImport } from './routes/tyres.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTestingLabRouteImport } from './routes/admin.testing-lab'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminVehiclesRouteImport } from './routes/_authenticated/admin.vehicles'
import { Route as AuthenticatedAdminTyresRouteImport } from './routes/_authenticated/admin.tyres'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin.sections'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminReviewRequestsRouteImport } from './routes/_authenticated/admin.review-requests'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminChangePasswordRouteImport } from './routes/_authenticated/admin.change-password'
import { Route as AuthenticatedAdminCatalogueRouteImport } from './routes/_authenticated/admin.catalogue'
import { Route as AuthenticatedAdminBusinessRouteImport } from './routes/_authenticated/admin.business'
import { Route as AuthenticatedAdminBrandsRouteImport } from './routes/_authenticated/admin.brands'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminTyresIndexRouteImport } from './routes/_authenticated/admin.tyres.index'
import { Route as AuthenticatedAdminSectionsIndexRouteImport } from './routes/_authenticated/admin.sections.index'
import { Route as AuthenticatedAdminCatalogueIndexRouteImport } from './routes/_authenticated/admin.catalogue.index'
import { Route as AuthenticatedAdminBrandsIndexRouteImport } from './routes/_authenticated/admin.brands.index'
import { Route as AuthenticatedAdminVehiclesReviewRouteImport } from './routes/_authenticated/admin.vehicles.review'
import { Route as AuthenticatedAdminVehiclesImportRouteImport } from './routes/_authenticated/admin.vehicles.import'
import { Route as AuthenticatedAdminVehiclesModelIdRouteImport } from './routes/_authenticated/admin.vehicles.$modelId'
import { Route as AuthenticatedAdminTyresNewRouteImport } from './routes/_authenticated/admin.tyres.new'
import { Route as AuthenticatedAdminTyresIdRouteImport } from './routes/_authenticated/admin.tyres.$id'
import { Route as AuthenticatedAdminSectionsIdRouteImport } from './routes/_authenticated/admin.sections.$id'
import { Route as AuthenticatedAdminProductsImportRouteImport } from './routes/_authenticated/admin.products.import'
import { Route as AuthenticatedAdminCatalogueTypesRouteImport } from './routes/_authenticated/admin.catalogue.types'
import { Route as AuthenticatedAdminCatalogueSettingsRouteImport } from './routes/_authenticated/admin.catalogue.settings'
import { Route as AuthenticatedAdminCatalogueReviewRouteImport } from './routes/_authenticated/admin.catalogue.review'
import { Route as AuthenticatedAdminCatalogueNewRouteImport } from './routes/_authenticated/admin.catalogue.new'
import { Route as AuthenticatedAdminCatalogueImportRouteImport } from './routes/_authenticated/admin.catalogue.import'
import { Route as AuthenticatedAdminCatalogueHomepageRouteImport } from './routes/_authenticated/admin.catalogue.homepage'
import { Route as AuthenticatedAdminCatalogueFitmentsRouteImport } from './routes/_authenticated/admin.catalogue.fitments'
import { Route as AuthenticatedAdminCatalogueIdRouteImport } from './routes/_authenticated/admin.catalogue.$id'
import { Route as AuthenticatedAdminBrandsNewRouteImport } from './routes/_authenticated/admin.brands.new'
import { Route as AuthenticatedAdminBrandsIdRouteImport } from './routes/_authenticated/admin.brands.$id'
import { Route as AuthenticatedAdminVehiclesConfigurationsConfigIdRouteImport } from './routes/_authenticated/admin.vehicles.configurations.$configId'
import { Route as AuthenticatedAdminVehiclesModelIdRecommendationsRouteImport } from './routes/_authenticated/admin.vehicles.$modelId.recommendations'
import { Route as AuthenticatedAdminTyresIdCompatRouteImport } from './routes/_authenticated/admin.tyres.$id.compat'
import { Route as AuthenticatedAdminProductsImportReviewRouteImport } from './routes/_authenticated/admin.products.import.review'
import { Route as AuthenticatedAdminCatalogueImportBatchIdRouteImport } from './routes/_authenticated/admin.catalogue.import.$batchId'

const TyresRoute = TyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => rootRouteImport,
} as any)
const TyreGuideRoute = TyreGuideRouteImport.update({
  id: '/tyre-guide',
  path: '/tyre-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancePartsRoute = MaintenancePartsRouteImport.update({
  id: '/maintenance-parts',
  path: '/maintenance-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const LubricantsRoute = LubricantsRouteImport.update({
  id: '/lubricants',
  path: '/lubricants',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarCareRoute = CarCareRouteImport.update({
  id: '/car-care',
  path: '/car-care',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditivesRoute = AdditivesRouteImport.update({
  id: '/additives',
  path: '/additives',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TyresSlugRoute = TyresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TyresRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTestingLabRoute = AdminTestingLabRouteImport.update({
  id: '/admin/testing-lab',
  path: '/admin/testing-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVehiclesRoute =
  AuthenticatedAdminVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTyresRoute = AuthenticatedAdminTyresRouteImport.update({
  id: '/tyres',
  path: '/tyres',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSectionsRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewRequestsRoute =
  AuthenticatedAdminReviewRequestsRouteImport.update({
    id: '/review-requests',
    path: '/review-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminChangePasswordRoute =
  AuthenticatedAdminChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogueRoute =
  AuthenticatedAdminCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessRoute =
  AuthenticatedAdminBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandsRoute =
  AuthenticatedAdminBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTyresIndexRoute =
  AuthenticatedAdminTyresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminSectionsIndexRoute =
  AuthenticatedAdminSectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSectionsRoute,
  } as any)
const AuthenticatedAdminCatalogueIndexRoute =
  AuthenticatedAdminCatalogueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminBrandsIndexRoute =
  AuthenticatedAdminBrandsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)
const AuthenticatedAdminVehiclesReviewRoute =
  AuthenticatedAdminVehiclesReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminVehiclesRoute,
  } as any)
const AuthenticatedAdminVehiclesImportRoute =
  AuthenticatedAdminVehiclesImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminVehiclesRoute,
  } as any)
const AuthenticatedAdminVehiclesModelIdRoute =
  AuthenticatedAdminVehiclesModelIdRouteImport.update({
    id: '/$modelId',
    path: '/$modelId',
    getParentRoute: () => AuthenticatedAdminVehiclesRoute,
  } as any)
const AuthenticatedAdminTyresNewRoute =
  AuthenticatedAdminTyresNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminTyresIdRoute =
  AuthenticatedAdminTyresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTyresRoute,
  } as any)
const AuthenticatedAdminSectionsIdRoute =
  AuthenticatedAdminSectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSectionsRoute,
  } as any)
const AuthenticatedAdminProductsImportRoute =
  AuthenticatedAdminProductsImportRouteImport.update({
    id: '/products/import',
    path: '/products/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogueTypesRoute =
  AuthenticatedAdminCatalogueTypesRouteImport.update({
    id: '/types',
    path: '/types',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueSettingsRoute =
  AuthenticatedAdminCatalogueSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueReviewRoute =
  AuthenticatedAdminCatalogueReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueNewRoute =
  AuthenticatedAdminCatalogueNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueImportRoute =
  AuthenticatedAdminCatalogueImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueHomepageRoute =
  AuthenticatedAdminCatalogueHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueFitmentsRoute =
  AuthenticatedAdminCatalogueFitmentsRouteImport.update({
    id: '/fitments',
    path: '/fitments',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminCatalogueIdRoute =
  AuthenticatedAdminCatalogueIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCatalogueRoute,
  } as any)
const AuthenticatedAdminBrandsNewRoute =
  AuthenticatedAdminBrandsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)
const AuthenticatedAdminBrandsIdRoute =
  AuthenticatedAdminBrandsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBrandsRoute,
  } as any)
const AuthenticatedAdminVehiclesConfigurationsConfigIdRoute =
  AuthenticatedAdminVehiclesConfigurationsConfigIdRouteImport.update({
    id: '/configurations/$configId',
    path: '/configurations/$configId',
    getParentRoute: () => AuthenticatedAdminVehiclesRoute,
  } as any)
const AuthenticatedAdminVehiclesModelIdRecommendationsRoute =
  AuthenticatedAdminVehiclesModelIdRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedAdminVehiclesModelIdRoute,
  } as any)
const AuthenticatedAdminTyresIdCompatRoute =
  AuthenticatedAdminTyresIdCompatRouteImport.update({
    id: '/compat',
    path: '/compat',
    getParentRoute: () => AuthenticatedAdminTyresIdRoute,
  } as any)
const AuthenticatedAdminProductsImportReviewRoute =
  AuthenticatedAdminProductsImportReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminProductsImportRoute,
  } as any)
const AuthenticatedAdminCatalogueImportBatchIdRoute =
  AuthenticatedAdminCatalogueImportBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedAdminCatalogueImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/additives': typeof AdditivesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/car-care': typeof CarCareRoute
  '/contact': typeof ContactRoute
  '/filters': typeof FiltersRoute
  '/lubricants': typeof LubricantsRoute
  '/maintenance-parts': typeof MaintenancePartsRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tyres/$slug': typeof TyresSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsRouteWithChildren
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRouteWithChildren
  '/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/review-requests': typeof AuthenticatedAdminReviewRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRouteWithChildren
  '/admin/tyres': typeof AuthenticatedAdminTyresRouteWithChildren
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRouteWithChildren
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/admin/catalogue/fitments': typeof AuthenticatedAdminCatalogueFitmentsRoute
  '/admin/catalogue/homepage': typeof AuthenticatedAdminCatalogueHomepageRoute
  '/admin/catalogue/import': typeof AuthenticatedAdminCatalogueImportRouteWithChildren
  '/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/admin/catalogue/review': typeof AuthenticatedAdminCatalogueReviewRoute
  '/admin/catalogue/settings': typeof AuthenticatedAdminCatalogueSettingsRoute
  '/admin/catalogue/types': typeof AuthenticatedAdminCatalogueTypesRoute
  '/admin/products/import': typeof AuthenticatedAdminProductsImportRouteWithChildren
  '/admin/sections/$id': typeof AuthenticatedAdminSectionsIdRoute
  '/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRouteWithChildren
  '/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/admin/vehicles/$modelId': typeof AuthenticatedAdminVehiclesModelIdRouteWithChildren
  '/admin/vehicles/import': typeof AuthenticatedAdminVehiclesImportRoute
  '/admin/vehicles/review': typeof AuthenticatedAdminVehiclesReviewRoute
  '/admin/brands/': typeof AuthenticatedAdminBrandsIndexRoute
  '/admin/catalogue/': typeof AuthenticatedAdminCatalogueIndexRoute
  '/admin/sections/': typeof AuthenticatedAdminSectionsIndexRoute
  '/admin/tyres/': typeof AuthenticatedAdminTyresIndexRoute
  '/admin/catalogue/import/$batchId': typeof AuthenticatedAdminCatalogueImportBatchIdRoute
  '/admin/products/import/review': typeof AuthenticatedAdminProductsImportReviewRoute
  '/admin/tyres/$id/compat': typeof AuthenticatedAdminTyresIdCompatRoute
  '/admin/vehicles/$modelId/recommendations': typeof AuthenticatedAdminVehiclesModelIdRecommendationsRoute
  '/admin/vehicles/configurations/$configId': typeof AuthenticatedAdminVehiclesConfigurationsConfigIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/additives': typeof AdditivesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/car-care': typeof CarCareRoute
  '/contact': typeof ContactRoute
  '/filters': typeof FiltersRoute
  '/lubricants': typeof LubricantsRoute
  '/maintenance-parts': typeof MaintenancePartsRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRouteWithChildren
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tyres/$slug': typeof TyresSlugRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/review-requests': typeof AuthenticatedAdminReviewRequestsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRouteWithChildren
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/admin/catalogue/fitments': typeof AuthenticatedAdminCatalogueFitmentsRoute
  '/admin/catalogue/homepage': typeof AuthenticatedAdminCatalogueHomepageRoute
  '/admin/catalogue/import': typeof AuthenticatedAdminCatalogueImportRouteWithChildren
  '/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/admin/catalogue/review': typeof AuthenticatedAdminCatalogueReviewRoute
  '/admin/catalogue/settings': typeof AuthenticatedAdminCatalogueSettingsRoute
  '/admin/catalogue/types': typeof AuthenticatedAdminCatalogueTypesRoute
  '/admin/products/import': typeof AuthenticatedAdminProductsImportRouteWithChildren
  '/admin/sections/$id': typeof AuthenticatedAdminSectionsIdRoute
  '/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRouteWithChildren
  '/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/admin/vehicles/$modelId': typeof AuthenticatedAdminVehiclesModelIdRouteWithChildren
  '/admin/vehicles/import': typeof AuthenticatedAdminVehiclesImportRoute
  '/admin/vehicles/review': typeof AuthenticatedAdminVehiclesReviewRoute
  '/admin/brands': typeof AuthenticatedAdminBrandsIndexRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueIndexRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsIndexRoute
  '/admin/tyres': typeof AuthenticatedAdminTyresIndexRoute
  '/admin/catalogue/import/$batchId': typeof AuthenticatedAdminCatalogueImportBatchIdRoute
  '/admin/products/import/review': typeof AuthenticatedAdminProductsImportReviewRoute
  '/admin/tyres/$id/compat': typeof AuthenticatedAdminTyresIdCompatRoute
  '/admin/vehicles/$modelId/recommendations': typeof AuthenticatedAdminVehiclesModelIdRecommendationsRoute
  '/admin/vehicles/configurations/$configId': typeof AuthenticatedAdminVehiclesConfigurationsConfigIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/additives': typeof AdditivesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/car-care': typeof CarCareRoute
  '/contact': typeof ContactRoute
  '/filters': typeof FiltersRoute
  '/lubricants': typeof LubricantsRoute
  '/maintenance-parts': typeof MaintenancePartsRoute
  '/offline': typeof OfflineRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tyre-guide': typeof TyreGuideRoute
  '/tyres': typeof TyresRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/testing-lab': typeof AdminTestingLabRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tyres/$slug': typeof TyresSlugRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/brands': typeof AuthenticatedAdminBrandsRouteWithChildren
  '/_authenticated/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/_authenticated/admin/catalogue': typeof AuthenticatedAdminCatalogueRouteWithChildren
  '/_authenticated/admin/change-password': typeof AuthenticatedAdminChangePasswordRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/review-requests': typeof AuthenticatedAdminReviewRequestsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRouteWithChildren
  '/_authenticated/admin/tyres': typeof AuthenticatedAdminTyresRouteWithChildren
  '/_authenticated/admin/vehicles': typeof AuthenticatedAdminVehiclesRouteWithChildren
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/brands/$id': typeof AuthenticatedAdminBrandsIdRoute
  '/_authenticated/admin/brands/new': typeof AuthenticatedAdminBrandsNewRoute
  '/_authenticated/admin/catalogue/$id': typeof AuthenticatedAdminCatalogueIdRoute
  '/_authenticated/admin/catalogue/fitments': typeof AuthenticatedAdminCatalogueFitmentsRoute
  '/_authenticated/admin/catalogue/homepage': typeof AuthenticatedAdminCatalogueHomepageRoute
  '/_authenticated/admin/catalogue/import': typeof AuthenticatedAdminCatalogueImportRouteWithChildren
  '/_authenticated/admin/catalogue/new': typeof AuthenticatedAdminCatalogueNewRoute
  '/_authenticated/admin/catalogue/review': typeof AuthenticatedAdminCatalogueReviewRoute
  '/_authenticated/admin/catalogue/settings': typeof AuthenticatedAdminCatalogueSettingsRoute
  '/_authenticated/admin/catalogue/types': typeof AuthenticatedAdminCatalogueTypesRoute
  '/_authenticated/admin/products/import': typeof AuthenticatedAdminProductsImportRouteWithChildren
  '/_authenticated/admin/sections/$id': typeof AuthenticatedAdminSectionsIdRoute
  '/_authenticated/admin/tyres/$id': typeof AuthenticatedAdminTyresIdRouteWithChildren
  '/_authenticated/admin/tyres/new': typeof AuthenticatedAdminTyresNewRoute
  '/_authenticated/admin/vehicles/$modelId': typeof AuthenticatedAdminVehiclesModelIdRouteWithChildren
  '/_authenticated/admin/vehicles/import': typeof AuthenticatedAdminVehiclesImportRoute
  '/_authenticated/admin/vehicles/review': typeof AuthenticatedAdminVehiclesReviewRoute
  '/_authenticated/admin/brands/': typeof AuthenticatedAdminBrandsIndexRoute
  '/_authenticated/admin/catalogue/': typeof AuthenticatedAdminCatalogueIndexRoute
  '/_authenticated/admin/sections/': typeof AuthenticatedAdminSectionsIndexRoute
  '/_authenticated/admin/tyres/': typeof AuthenticatedAdminTyresIndexRoute
  '/_authenticated/admin/catalogue/import/$batchId': typeof AuthenticatedAdminCatalogueImportBatchIdRoute
  '/_authenticated/admin/products/import/review': typeof AuthenticatedAdminProductsImportReviewRoute
  '/_authenticated/admin/tyres/$id/compat': typeof AuthenticatedAdminTyresIdCompatRoute
  '/_authenticated/admin/vehicles/$modelId/recommendations': typeof AuthenticatedAdminVehiclesModelIdRecommendationsRoute
  '/_authenticated/admin/vehicles/configurations/$configId': typeof AuthenticatedAdminVehiclesConfigurationsConfigIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/additives'
    | '/auth'
    | '/blog'
    | '/car-care'
    | '/contact'
    | '/filters'
    | '/lubricants'
    | '/maintenance-parts'
    | '/offline'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin'
    | '/admin/testing-lab'
    | '/blog/$slug'
    | '/tyres/$slug'
    | '/admin/activity'
    | '/admin/articles'
    | '/admin/brands'
    | '/admin/business'
    | '/admin/catalogue'
    | '/admin/change-password'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/review-requests'
    | '/admin/reviews'
    | '/admin/sections'
    | '/admin/tyres'
    | '/admin/vehicles'
    | '/admin/videos'
    | '/admin/'
    | '/admin/brands/$id'
    | '/admin/brands/new'
    | '/admin/catalogue/$id'
    | '/admin/catalogue/fitments'
    | '/admin/catalogue/homepage'
    | '/admin/catalogue/import'
    | '/admin/catalogue/new'
    | '/admin/catalogue/review'
    | '/admin/catalogue/settings'
    | '/admin/catalogue/types'
    | '/admin/products/import'
    | '/admin/sections/$id'
    | '/admin/tyres/$id'
    | '/admin/tyres/new'
    | '/admin/vehicles/$modelId'
    | '/admin/vehicles/import'
    | '/admin/vehicles/review'
    | '/admin/brands/'
    | '/admin/catalogue/'
    | '/admin/sections/'
    | '/admin/tyres/'
    | '/admin/catalogue/import/$batchId'
    | '/admin/products/import/review'
    | '/admin/tyres/$id/compat'
    | '/admin/vehicles/$modelId/recommendations'
    | '/admin/vehicles/configurations/$configId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/additives'
    | '/auth'
    | '/blog'
    | '/car-care'
    | '/contact'
    | '/filters'
    | '/lubricants'
    | '/maintenance-parts'
    | '/offline'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/admin/testing-lab'
    | '/blog/$slug'
    | '/tyres/$slug'
    | '/admin/activity'
    | '/admin/articles'
    | '/admin/business'
    | '/admin/change-password'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/review-requests'
    | '/admin/reviews'
    | '/admin/vehicles'
    | '/admin/videos'
    | '/admin'
    | '/admin/brands/$id'
    | '/admin/brands/new'
    | '/admin/catalogue/$id'
    | '/admin/catalogue/fitments'
    | '/admin/catalogue/homepage'
    | '/admin/catalogue/import'
    | '/admin/catalogue/new'
    | '/admin/catalogue/review'
    | '/admin/catalogue/settings'
    | '/admin/catalogue/types'
    | '/admin/products/import'
    | '/admin/sections/$id'
    | '/admin/tyres/$id'
    | '/admin/tyres/new'
    | '/admin/vehicles/$modelId'
    | '/admin/vehicles/import'
    | '/admin/vehicles/review'
    | '/admin/brands'
    | '/admin/catalogue'
    | '/admin/sections'
    | '/admin/tyres'
    | '/admin/catalogue/import/$batchId'
    | '/admin/products/import/review'
    | '/admin/tyres/$id/compat'
    | '/admin/vehicles/$modelId/recommendations'
    | '/admin/vehicles/configurations/$configId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessories'
    | '/additives'
    | '/auth'
    | '/blog'
    | '/car-care'
    | '/contact'
    | '/filters'
    | '/lubricants'
    | '/maintenance-parts'
    | '/offline'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/tyre-guide'
    | '/tyres'
    | '/_authenticated/admin'
    | '/admin/testing-lab'
    | '/blog/$slug'
    | '/tyres/$slug'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/brands'
    | '/_authenticated/admin/business'
    | '/_authenticated/admin/catalogue'
    | '/_authenticated/admin/change-password'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/review-requests'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/sections'
    | '/_authenticated/admin/tyres'
    | '/_authenticated/admin/vehicles'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/brands/$id'
    | '/_authenticated/admin/brands/new'
    | '/_authenticated/admin/catalogue/$id'
    | '/_authenticated/admin/catalogue/fitments'
    | '/_authenticated/admin/catalogue/homepage'
    | '/_authenticated/admin/catalogue/import'
    | '/_authenticated/admin/catalogue/new'
    | '/_authenticated/admin/catalogue/review'
    | '/_authenticated/admin/catalogue/settings'
    | '/_authenticated/admin/catalogue/types'
    | '/_authenticated/admin/products/import'
    | '/_authenticated/admin/sections/$id'
    | '/_authenticated/admin/tyres/$id'
    | '/_authenticated/admin/tyres/new'
    | '/_authenticated/admin/vehicles/$modelId'
    | '/_authenticated/admin/vehicles/import'
    | '/_authenticated/admin/vehicles/review'
    | '/_authenticated/admin/brands/'
    | '/_authenticated/admin/catalogue/'
    | '/_authenticated/admin/sections/'
    | '/_authenticated/admin/tyres/'
    | '/_authenticated/admin/catalogue/import/$batchId'
    | '/_authenticated/admin/products/import/review'
    | '/_authenticated/admin/tyres/$id/compat'
    | '/_authenticated/admin/vehicles/$modelId/recommendations'
    | '/_authenticated/admin/vehicles/configurations/$configId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AdditivesRoute: typeof AdditivesRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CarCareRoute: typeof CarCareRoute
  ContactRoute: typeof ContactRoute
  FiltersRoute: typeof FiltersRoute
  LubricantsRoute: typeof LubricantsRoute
  MaintenancePartsRoute: typeof MaintenancePartsRoute
  OfflineRoute: typeof OfflineRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TyreGuideRoute: typeof TyreGuideRoute
  TyresRoute: typeof TyresRouteWithChildren
  AdminTestingLabRoute: typeof AdminTestingLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tyres': {
      id: '/tyres'
      path: '/tyres'
      fullPath: '/tyres'
      preLoaderRoute: typeof TyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyre-guide': {
      id: '/tyre-guide'
      path: '/tyre-guide'
      fullPath: '/tyre-guide'
      preLoaderRoute: typeof TyreGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-parts': {
      id: '/maintenance-parts'
      path: '/maintenance-parts'
      fullPath: '/maintenance-parts'
      preLoaderRoute: typeof MaintenancePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lubricants': {
      id: '/lubricants'
      path: '/lubricants'
      fullPath: '/lubricants'
      preLoaderRoute: typeof LubricantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-care': {
      id: '/car-care'
      path: '/car-care'
      fullPath: '/car-care'
      preLoaderRoute: typeof CarCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additives': {
      id: '/additives'
      path: '/additives'
      fullPath: '/additives'
      preLoaderRoute: typeof AdditivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyres/$slug': {
      id: '/tyres/$slug'
      path: '/$slug'
      fullPath: '/tyres/$slug'
      preLoaderRoute: typeof TyresSlugRouteImport
      parentRoute: typeof TyresRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/testing-lab': {
      id: '/admin/testing-lab'
      path: '/admin/testing-lab'
      fullPath: '/admin/testing-lab'
      preLoaderRoute: typeof AdminTestingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vehicles': {
      id: '/_authenticated/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tyres': {
      id: '/_authenticated/admin/tyres'
      path: '/tyres'
      fullPath: '/admin/tyres'
      preLoaderRoute: typeof AuthenticatedAdminTyresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/review-requests': {
      id: '/_authenticated/admin/review-requests'
      path: '/review-requests'
      fullPath: '/admin/review-requests'
      preLoaderRoute: typeof AuthenticatedAdminReviewRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/change-password': {
      id: '/_authenticated/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AuthenticatedAdminChangePasswordRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogue': {
      id: '/_authenticated/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business': {
      id: '/_authenticated/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AuthenticatedAdminBusinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/brands': {
      id: '/_authenticated/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AuthenticatedAdminBrandsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tyres/': {
      id: '/_authenticated/admin/tyres/'
      path: '/'
      fullPath: '/admin/tyres/'
      preLoaderRoute: typeof AuthenticatedAdminTyresIndexRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/sections/': {
      id: '/_authenticated/admin/sections/'
      path: '/'
      fullPath: '/admin/sections/'
      preLoaderRoute: typeof AuthenticatedAdminSectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSectionsRoute
    }
    '/_authenticated/admin/catalogue/': {
      id: '/_authenticated/admin/catalogue/'
      path: '/'
      fullPath: '/admin/catalogue/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/brands/': {
      id: '/_authenticated/admin/brands/'
      path: '/'
      fullPath: '/admin/brands/'
      preLoaderRoute: typeof AuthenticatedAdminBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
    '/_authenticated/admin/vehicles/review': {
      id: '/_authenticated/admin/vehicles/review'
      path: '/review'
      fullPath: '/admin/vehicles/review'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesReviewRouteImport
      parentRoute: typeof AuthenticatedAdminVehiclesRoute
    }
    '/_authenticated/admin/vehicles/import': {
      id: '/_authenticated/admin/vehicles/import'
      path: '/import'
      fullPath: '/admin/vehicles/import'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesImportRouteImport
      parentRoute: typeof AuthenticatedAdminVehiclesRoute
    }
    '/_authenticated/admin/vehicles/$modelId': {
      id: '/_authenticated/admin/vehicles/$modelId'
      path: '/$modelId'
      fullPath: '/admin/vehicles/$modelId'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesModelIdRouteImport
      parentRoute: typeof AuthenticatedAdminVehiclesRoute
    }
    '/_authenticated/admin/tyres/new': {
      id: '/_authenticated/admin/tyres/new'
      path: '/new'
      fullPath: '/admin/tyres/new'
      preLoaderRoute: typeof AuthenticatedAdminTyresNewRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/tyres/$id': {
      id: '/_authenticated/admin/tyres/$id'
      path: '/$id'
      fullPath: '/admin/tyres/$id'
      preLoaderRoute: typeof AuthenticatedAdminTyresIdRouteImport
      parentRoute: typeof AuthenticatedAdminTyresRoute
    }
    '/_authenticated/admin/sections/$id': {
      id: '/_authenticated/admin/sections/$id'
      path: '/$id'
      fullPath: '/admin/sections/$id'
      preLoaderRoute: typeof AuthenticatedAdminSectionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminSectionsRoute
    }
    '/_authenticated/admin/products/import': {
      id: '/_authenticated/admin/products/import'
      path: '/products/import'
      fullPath: '/admin/products/import'
      preLoaderRoute: typeof AuthenticatedAdminProductsImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogue/types': {
      id: '/_authenticated/admin/catalogue/types'
      path: '/types'
      fullPath: '/admin/catalogue/types'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueTypesRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/settings': {
      id: '/_authenticated/admin/catalogue/settings'
      path: '/settings'
      fullPath: '/admin/catalogue/settings'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/review': {
      id: '/_authenticated/admin/catalogue/review'
      path: '/review'
      fullPath: '/admin/catalogue/review'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueReviewRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/new': {
      id: '/_authenticated/admin/catalogue/new'
      path: '/new'
      fullPath: '/admin/catalogue/new'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueNewRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/import': {
      id: '/_authenticated/admin/catalogue/import'
      path: '/import'
      fullPath: '/admin/catalogue/import'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueImportRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/homepage': {
      id: '/_authenticated/admin/catalogue/homepage'
      path: '/homepage'
      fullPath: '/admin/catalogue/homepage'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/fitments': {
      id: '/_authenticated/admin/catalogue/fitments'
      path: '/fitments'
      fullPath: '/admin/catalogue/fitments'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueFitmentsRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/catalogue/$id': {
      id: '/_authenticated/admin/catalogue/$id'
      path: '/$id'
      fullPath: '/admin/catalogue/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueIdRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueRoute
    }
    '/_authenticated/admin/brands/new': {
      id: '/_authenticated/admin/brands/new'
      path: '/new'
      fullPath: '/admin/brands/new'
      preLoaderRoute: typeof AuthenticatedAdminBrandsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
    '/_authenticated/admin/brands/$id': {
      id: '/_authenticated/admin/brands/$id'
      path: '/$id'
      fullPath: '/admin/brands/$id'
      preLoaderRoute: typeof AuthenticatedAdminBrandsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBrandsRoute
    }
    '/_authenticated/admin/vehicles/configurations/$configId': {
      id: '/_authenticated/admin/vehicles/configurations/$configId'
      path: '/configurations/$configId'
      fullPath: '/admin/vehicles/configurations/$configId'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesConfigurationsConfigIdRouteImport
      parentRoute: typeof AuthenticatedAdminVehiclesRoute
    }
    '/_authenticated/admin/vehicles/$modelId/recommendations': {
      id: '/_authenticated/admin/vehicles/$modelId/recommendations'
      path: '/recommendations'
      fullPath: '/admin/vehicles/$modelId/recommendations'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesModelIdRecommendationsRouteImport
      parentRoute: typeof AuthenticatedAdminVehiclesModelIdRoute
    }
    '/_authenticated/admin/tyres/$id/compat': {
      id: '/_authenticated/admin/tyres/$id/compat'
      path: '/compat'
      fullPath: '/admin/tyres/$id/compat'
      preLoaderRoute: typeof AuthenticatedAdminTyresIdCompatRouteImport
      parentRoute: typeof AuthenticatedAdminTyresIdRoute
    }
    '/_authenticated/admin/products/import/review': {
      id: '/_authenticated/admin/products/import/review'
      path: '/review'
      fullPath: '/admin/products/import/review'
      preLoaderRoute: typeof AuthenticatedAdminProductsImportReviewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsImportRoute
    }
    '/_authenticated/admin/catalogue/import/$batchId': {
      id: '/_authenticated/admin/catalogue/import/$batchId'
      path: '/$batchId'
      fullPath: '/admin/catalogue/import/$batchId'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueImportBatchIdRouteImport
      parentRoute: typeof AuthenticatedAdminCatalogueImportRoute
    }
  }
}

interface AuthenticatedAdminBrandsRouteChildren {
  AuthenticatedAdminBrandsIdRoute: typeof AuthenticatedAdminBrandsIdRoute
  AuthenticatedAdminBrandsNewRoute: typeof AuthenticatedAdminBrandsNewRoute
  AuthenticatedAdminBrandsIndexRoute: typeof AuthenticatedAdminBrandsIndexRoute
}

const AuthenticatedAdminBrandsRouteChildren: AuthenticatedAdminBrandsRouteChildren =
  {
    AuthenticatedAdminBrandsIdRoute: AuthenticatedAdminBrandsIdRoute,
    AuthenticatedAdminBrandsNewRoute: AuthenticatedAdminBrandsNewRoute,
    AuthenticatedAdminBrandsIndexRoute: AuthenticatedAdminBrandsIndexRoute,
  }

const AuthenticatedAdminBrandsRouteWithChildren =
  AuthenticatedAdminBrandsRoute._addFileChildren(
    AuthenticatedAdminBrandsRouteChildren,
  )

interface AuthenticatedAdminCatalogueImportRouteChildren {
  AuthenticatedAdminCatalogueImportBatchIdRoute: typeof AuthenticatedAdminCatalogueImportBatchIdRoute
}

const AuthenticatedAdminCatalogueImportRouteChildren: AuthenticatedAdminCatalogueImportRouteChildren =
  {
    AuthenticatedAdminCatalogueImportBatchIdRoute:
      AuthenticatedAdminCatalogueImportBatchIdRoute,
  }

const AuthenticatedAdminCatalogueImportRouteWithChildren =
  AuthenticatedAdminCatalogueImportRoute._addFileChildren(
    AuthenticatedAdminCatalogueImportRouteChildren,
  )

interface AuthenticatedAdminCatalogueRouteChildren {
  AuthenticatedAdminCatalogueIdRoute: typeof AuthenticatedAdminCatalogueIdRoute
  AuthenticatedAdminCatalogueFitmentsRoute: typeof AuthenticatedAdminCatalogueFitmentsRoute
  AuthenticatedAdminCatalogueHomepageRoute: typeof AuthenticatedAdminCatalogueHomepageRoute
  AuthenticatedAdminCatalogueImportRoute: typeof AuthenticatedAdminCatalogueImportRouteWithChildren
  AuthenticatedAdminCatalogueNewRoute: typeof AuthenticatedAdminCatalogueNewRoute
  AuthenticatedAdminCatalogueReviewRoute: typeof AuthenticatedAdminCatalogueReviewRoute
  AuthenticatedAdminCatalogueSettingsRoute: typeof AuthenticatedAdminCatalogueSettingsRoute
  AuthenticatedAdminCatalogueTypesRoute: typeof AuthenticatedAdminCatalogueTypesRoute
  AuthenticatedAdminCatalogueIndexRoute: typeof AuthenticatedAdminCatalogueIndexRoute
}

const AuthenticatedAdminCatalogueRouteChildren: AuthenticatedAdminCatalogueRouteChildren =
  {
    AuthenticatedAdminCatalogueIdRoute: AuthenticatedAdminCatalogueIdRoute,
    AuthenticatedAdminCatalogueFitmentsRoute:
      AuthenticatedAdminCatalogueFitmentsRoute,
    AuthenticatedAdminCatalogueHomepageRoute:
      AuthenticatedAdminCatalogueHomepageRoute,
    AuthenticatedAdminCatalogueImportRoute:
      AuthenticatedAdminCatalogueImportRouteWithChildren,
    AuthenticatedAdminCatalogueNewRoute: AuthenticatedAdminCatalogueNewRoute,
    AuthenticatedAdminCatalogueReviewRoute:
      AuthenticatedAdminCatalogueReviewRoute,
    AuthenticatedAdminCatalogueSettingsRoute:
      AuthenticatedAdminCatalogueSettingsRoute,
    AuthenticatedAdminCatalogueTypesRoute:
      AuthenticatedAdminCatalogueTypesRoute,
    AuthenticatedAdminCatalogueIndexRoute:
      AuthenticatedAdminCatalogueIndexRoute,
  }

const AuthenticatedAdminCatalogueRouteWithChildren =
  AuthenticatedAdminCatalogueRoute._addFileChildren(
    AuthenticatedAdminCatalogueRouteChildren,
  )

interface AuthenticatedAdminSectionsRouteChildren {
  AuthenticatedAdminSectionsIdRoute: typeof AuthenticatedAdminSectionsIdRoute
  AuthenticatedAdminSectionsIndexRoute: typeof AuthenticatedAdminSectionsIndexRoute
}

const AuthenticatedAdminSectionsRouteChildren: AuthenticatedAdminSectionsRouteChildren =
  {
    AuthenticatedAdminSectionsIdRoute: AuthenticatedAdminSectionsIdRoute,
    AuthenticatedAdminSectionsIndexRoute: AuthenticatedAdminSectionsIndexRoute,
  }

const AuthenticatedAdminSectionsRouteWithChildren =
  AuthenticatedAdminSectionsRoute._addFileChildren(
    AuthenticatedAdminSectionsRouteChildren,
  )

interface AuthenticatedAdminTyresIdRouteChildren {
  AuthenticatedAdminTyresIdCompatRoute: typeof AuthenticatedAdminTyresIdCompatRoute
}

const AuthenticatedAdminTyresIdRouteChildren: AuthenticatedAdminTyresIdRouteChildren =
  {
    AuthenticatedAdminTyresIdCompatRoute: AuthenticatedAdminTyresIdCompatRoute,
  }

const AuthenticatedAdminTyresIdRouteWithChildren =
  AuthenticatedAdminTyresIdRoute._addFileChildren(
    AuthenticatedAdminTyresIdRouteChildren,
  )

interface AuthenticatedAdminTyresRouteChildren {
  AuthenticatedAdminTyresIdRoute: typeof AuthenticatedAdminTyresIdRouteWithChildren
  AuthenticatedAdminTyresNewRoute: typeof AuthenticatedAdminTyresNewRoute
  AuthenticatedAdminTyresIndexRoute: typeof AuthenticatedAdminTyresIndexRoute
}

const AuthenticatedAdminTyresRouteChildren: AuthenticatedAdminTyresRouteChildren =
  {
    AuthenticatedAdminTyresIdRoute: AuthenticatedAdminTyresIdRouteWithChildren,
    AuthenticatedAdminTyresNewRoute: AuthenticatedAdminTyresNewRoute,
    AuthenticatedAdminTyresIndexRoute: AuthenticatedAdminTyresIndexRoute,
  }

const AuthenticatedAdminTyresRouteWithChildren =
  AuthenticatedAdminTyresRoute._addFileChildren(
    AuthenticatedAdminTyresRouteChildren,
  )

interface AuthenticatedAdminVehiclesModelIdRouteChildren {
  AuthenticatedAdminVehiclesModelIdRecommendationsRoute: typeof AuthenticatedAdminVehiclesModelIdRecommendationsRoute
}

const AuthenticatedAdminVehiclesModelIdRouteChildren: AuthenticatedAdminVehiclesModelIdRouteChildren =
  {
    AuthenticatedAdminVehiclesModelIdRecommendationsRoute:
      AuthenticatedAdminVehiclesModelIdRecommendationsRoute,
  }

const AuthenticatedAdminVehiclesModelIdRouteWithChildren =
  AuthenticatedAdminVehiclesModelIdRoute._addFileChildren(
    AuthenticatedAdminVehiclesModelIdRouteChildren,
  )

interface AuthenticatedAdminVehiclesRouteChildren {
  AuthenticatedAdminVehiclesModelIdRoute: typeof AuthenticatedAdminVehiclesModelIdRouteWithChildren
  AuthenticatedAdminVehiclesImportRoute: typeof AuthenticatedAdminVehiclesImportRoute
  AuthenticatedAdminVehiclesReviewRoute: typeof AuthenticatedAdminVehiclesReviewRoute
  AuthenticatedAdminVehiclesConfigurationsConfigIdRoute: typeof AuthenticatedAdminVehiclesConfigurationsConfigIdRoute
}

const AuthenticatedAdminVehiclesRouteChildren: AuthenticatedAdminVehiclesRouteChildren =
  {
    AuthenticatedAdminVehiclesModelIdRoute:
      AuthenticatedAdminVehiclesModelIdRouteWithChildren,
    AuthenticatedAdminVehiclesImportRoute:
      AuthenticatedAdminVehiclesImportRoute,
    AuthenticatedAdminVehiclesReviewRoute:
      AuthenticatedAdminVehiclesReviewRoute,
    AuthenticatedAdminVehiclesConfigurationsConfigIdRoute:
      AuthenticatedAdminVehiclesConfigurationsConfigIdRoute,
  }

const AuthenticatedAdminVehiclesRouteWithChildren =
  AuthenticatedAdminVehiclesRoute._addFileChildren(
    AuthenticatedAdminVehiclesRouteChildren,
  )

interface AuthenticatedAdminProductsImportRouteChildren {
  AuthenticatedAdminProductsImportReviewRoute: typeof AuthenticatedAdminProductsImportReviewRoute
}

const AuthenticatedAdminProductsImportRouteChildren: AuthenticatedAdminProductsImportRouteChildren =
  {
    AuthenticatedAdminProductsImportReviewRoute:
      AuthenticatedAdminProductsImportReviewRoute,
  }

const AuthenticatedAdminProductsImportRouteWithChildren =
  AuthenticatedAdminProductsImportRoute._addFileChildren(
    AuthenticatedAdminProductsImportRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminBrandsRoute: typeof AuthenticatedAdminBrandsRouteWithChildren
  AuthenticatedAdminBusinessRoute: typeof AuthenticatedAdminBusinessRoute
  AuthenticatedAdminCatalogueRoute: typeof AuthenticatedAdminCatalogueRouteWithChildren
  AuthenticatedAdminChangePasswordRoute: typeof AuthenticatedAdminChangePasswordRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminReviewRequestsRoute: typeof AuthenticatedAdminReviewRequestsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSectionsRoute: typeof AuthenticatedAdminSectionsRouteWithChildren
  AuthenticatedAdminTyresRoute: typeof AuthenticatedAdminTyresRouteWithChildren
  AuthenticatedAdminVehiclesRoute: typeof AuthenticatedAdminVehiclesRouteWithChildren
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductsImportRoute: typeof AuthenticatedAdminProductsImportRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminBrandsRoute: AuthenticatedAdminBrandsRouteWithChildren,
  AuthenticatedAdminBusinessRoute: AuthenticatedAdminBusinessRoute,
  AuthenticatedAdminCatalogueRoute:
    AuthenticatedAdminCatalogueRouteWithChildren,
  AuthenticatedAdminChangePasswordRoute: AuthenticatedAdminChangePasswordRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminReviewRequestsRoute: AuthenticatedAdminReviewRequestsRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSectionsRoute: AuthenticatedAdminSectionsRouteWithChildren,
  AuthenticatedAdminTyresRoute: AuthenticatedAdminTyresRouteWithChildren,
  AuthenticatedAdminVehiclesRoute: AuthenticatedAdminVehiclesRouteWithChildren,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductsImportRoute:
    AuthenticatedAdminProductsImportRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TyresRouteChildren {
  TyresSlugRoute: typeof TyresSlugRoute
}

const TyresRouteChildren: TyresRouteChildren = {
  TyresSlugRoute: TyresSlugRoute,
}

const TyresRouteWithChildren = TyresRoute._addFileChildren(TyresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  AdditivesRoute: AdditivesRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CarCareRoute: CarCareRoute,
  ContactRoute: ContactRoute,
  FiltersRoute: FiltersRoute,
  LubricantsRoute: LubricantsRoute,
  MaintenancePartsRoute: MaintenancePartsRoute,
  OfflineRoute: OfflineRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TyreGuideRoute: TyreGuideRoute,
  TyresRoute: TyresRouteWithChildren,
  AdminTestingLabRoute: AdminTestingLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
